# Name of your GitHub Actions workflow
name: Deploy Website to S3

# Define when this workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches:
      - main  # Change this if your default branch has a different name

# A workflow can have multiple jobs
jobs:
  # This is our deployment job
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks
    steps:
      # Step 1: Check out your repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change this to your S3 bucket's region

      # Step 3: Deploy to S3
      - name: Deploy to S3
        run: |
          aws s3 sync . s3://realzzybucket --delete
          # The --delete flag removes files in the bucket that don't exist in your repository